//
//  WeatherScenePresenter.swift
//  WeatherApp
//
//  Created by PENUBOTHU, JANAKI RAMA KRISHNA PREETHAM (Accenture) on 11/24/17.
//  Copyright (c) 2017 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherScenePresentationLogic
{
    func presentTemparatureValues(_ weatherScreenModel: WeatherScreenModel)
}

class WeatherScenePresenter: WeatherScenePresentationLogic
{
    weak var viewController: WeatherSceneDisplayLogic?
    
    func presentTemparatureValues(_ weatherScreenModel: WeatherScreenModel) {
        viewController?.displayTemparature(weatherScreenModel)
    }
}
