//
//  WeatherSceneInteractor.swift
//  WeatherApp
//
//  Created by PENUBOTHU, JANAKI RAMA KRISHNA PREETHAM (Accenture) on 11/24/17.
//  Copyright (c) 2017 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherSceneBusinessLogic
{
    func getCurrentWeather()
}

protocol WeatherSceneDataStore
{
}

class WeatherSceneInteractor: WeatherSceneBusinessLogic, WeatherSceneDataStore, WeatherSceneWorkerDelegate
{
    var presenter: WeatherScenePresentationLogic?
    var worker: WeatherSceneWorker?
    
    init() {
        worker = WeatherSceneWorker()
        worker?.delegate = self
    }
    
    func getCurrentWeather() {
        worker?.downloadCurrentWeather()
    }
    
    func resultsForWeatherSucess(_ weatherScreenModel: WeatherScreenModel) {
        presenter?.presentTemparatureValues(weatherScreenModel)
    }
}
