//
//  WeatherSceneViewController.swift
//  WeatherApp
//
//  Created by PENUBOTHU, JANAKI RAMA KRISHNA PREETHAM (Accenture) on 11/24/17.
//  Copyright (c) 2017 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherSceneDisplayLogic: class
{
    func displayTemparature(_ weatherScreenModel: WeatherScreenModel)
    
}

class WeatherSceneViewController: UIViewController, WeatherSceneDisplayLogic, UITableViewDelegate, UITableViewDataSource
{
    var interactor: WeatherSceneBusinessLogic?
    var router: (NSObjectProtocol & WeatherSceneRoutingLogic & WeatherSceneDataPassing)?
    
    @IBOutlet weak var currentDateLabel: UILabel!
    @IBOutlet weak var currentTemparatureLabel: UILabel!
    @IBOutlet weak var currentLocationLabel: UILabel!
    @IBOutlet weak var currentTemparatureImageView: UIImageView!
    @IBOutlet weak var currentTemparatureTypeLabel: UILabel!
    @IBOutlet weak var weatherVCTableView: UITableView!
    
    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = WeatherSceneInteractor()
        let presenter = WeatherScenePresenter()
        let router = WeatherSceneRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        weatherVCTableView.delegate = self
        weatherVCTableView.dataSource = self
        interactor?.getCurrentWeather()
    }
    
    func numberOfSections(in tableView: UITableView) -> Int
    {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int
    {
        return 6
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell
    {
        let weatherCell = tableView.dequeueReusableCell(withIdentifier: "weatheTableViewCell", for: indexPath)
        
        return weatherCell
    }
    
    func displayTemparature(_ weatherScreenModel: WeatherScreenModel) {
        currentLocationLabel.text = weatherScreenModel.cityName
        currentTemparatureLabel.text = String(weatherScreenModel.currentTemp) + "°"
        currentTemparatureTypeLabel.text = weatherScreenModel.weatherType
        currentDateLabel.text = weatherScreenModel.currentDate
        currentTemparatureImageView.image = UIImage.init(named: weatherScreenModel.weatherType)
    }
}
